name: Bug report
description: Nahlášení chyby nalezené při testování
title: "[Module] Stručný popis"
labels: ["bug"]
body:
  - type: input
    id: severity
    attributes:
      label: Severity (Critical/High/Medium/Low)
      placeholder: "High"
    validations:
      required: true
  - type: input
    id: priority
    attributes:
      label: Priority (High/Medium/Low)
      placeholder: "High"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Kroky k reprodukci
      placeholder: "1) ...\n2) ..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Očekávané chování
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Skutečné chování
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Prostředí
      placeholder: "Chrome 119 / Windows 11"
  - type: textarea
    id: attachments
    attributes:
      label: Přílohy
      description: "Odkazy na screenshoty"